### PR TITLE
#1 Added profile of lcs2022011

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
Screenshot 2023-02-04 191141
Added profile of LCS2022011

### CODE REVIEW

**Comment by SameepAher** [comment]
@akhilender-bongirwar Looks good to me!

Just add a screenshot which shows the url as well as the JSON data, in your PR description (as clearly stated in the issue). **Note:** GitHub allows you to edit comments, so you can edit the PR description to add the screenshot.

Will accept this PR once the above mentioned changes are made.

**Comment by akhilender-bongirwar** [comment]
image

**Comment by SameepAher** [comment]
This screenshot is fine.

The code changes in your previous commit were perfect. You have removed `[` and `]` in `profiles.json` in your new commit, which doesn't make any sense.

Make a new commit ensuring proper code changes and I'll accept the PR.

**Comment by akhilender-bongirwar** [comment]
Sir, I have removed [ ] by mistake last time. I have added them now, please check Sir.

**Comment by SameepAher** [comment]
> Sir, I have removed [ ] by mistake last time. I have added them now, please check Sir.

You need to push the code to make the changes visible.

Also, sorry for the confusion. You need to attach a screenshot  which returns your profile's data by roll number, so replace the older screenshot with a new screenshot considering this.

The url in your case should be localhost:3000/profiles/lcs2022011

**Comment by akhilender-bongirwar** [comment]
Sir, I have made the required changes. Please check, sir.
Screenshot (22)

**Comment by SameepAher** [comment]
@akhilender-bongirwar you are not required to edit `index.html`. So, just remove all the changes you've made in `index.html`, push the code and I'll accept the PR.

**Comment by SameepAher** [comment]
@akhilender-bongirwar the `14th line` in `index.html` should be
`<a href="./profiles/lcs2020000">/profiles/lcs2020000</a>`

**Comment by SameepAher** [comment]
@akhilender-bongirwar Accepted!

**Pull request closed without merging**
