### PR TITLE
added info of lcs2022057

### PR DESCRIPTION
**Pull request by Yash7426**

### CODE REVIEW

**Comment by SameepAher** [comment]
@Yash7426 The changes in `profiles.json` are perfect.

**Some changes required:**
- There is ***no need*** to edit `index.html`. So remove any changes you've made in that file.
- There is ***no need*** to create `public/profiles/lcs2022057.json`. You just need to directly add / edit in `profiles.json` (you have correctly made the changes in `profiles.json`). So remove `public/profiles/lcs2022057.json` from your project folder.
- As the issue description states - Attach a screenshot which shows the url as well as the JSON data, in your PR description, not as a separate file in the project folder. So remove `ss.png` from the project folder and add the screenshot in the PR description
- Also, add `Fixes: #1` (ensure `#1` links to the issue) in your PR description, which makes it clear for what issue this PR is made for.


Will accept the PR once these changes are made.

**Comment by Yash7426** [comment]
ss

**Comment by Yash7426** [comment]
Fixes #1

**Comment by Yash7426** [comment]
Screenshot 2023-02-04 194143
Fixes: #1

**Pull request closed without merging**
