### PR TITLE
adding details.html

### PR DESCRIPTION
**Pull request by Roar022**

### CODE REVIEW

**Comment by SameepAher** [comment]
@Roar022 The changes in `profiles.json` are perfect.

**Some changes required:**

- There is ***no need*** to edit `index.html`. So remove any changes you've made in that file.
- Attach a screenshot which shows the url as well as the JSON data, in your PR description (the issue description clearly states this).
- Also, add `Fixes: #1` (ensure `#1` links to the issue) in your PR description, which makes it clear for what issue this PR is made for.

Will accept the PR once these changes are made.

**Comment by Roar022** [comment]
Screenshot (146)
Fixes: #1

**Comment by SameepAher** [comment]
The screenshot looks fine.

> There is no need to edit index.html. So remove any changes you've made in that file.
@Roar022 In case you forgot.

Resolve this and push the new code. I'll accept the PR then.

**Comment by SameepAher** [comment]
@Roar022 Accepted!

**Pull request closed without merging**
