### PR TITLE
updated profiles.json and index.html

### PR DESCRIPTION
**Pull request by AkhileshJyotishi**
1. updated profiles.json

Screenshot (76)

fixes: #1

### CODE REVIEW

**Comment by SameepAher** [comment]
@AkhileshJyotishi It is not required to edit `index.html`, so remove any changes in it and push the new code.

Otherwise, everything including the PR description is perfect and to the point.

I'll accept the PR once you resolve the above mentioned.

**Comment by AkhileshJyotishi** [comment]
removed the changes in index.html

**Comment by SameepAher** [comment]
> removed the changes in index.html

`line 14` in `index.html` should be `<a href="./profiles/lcs2020000">/profiles/lcs2020000</a>`. Make this change and push the new code.

**Comment by AkhileshJyotishi** [comment]
done this time!

**Comment by SameepAher** [comment]
@AkhileshJyotishi Accepted!

**Pull request closed without merging**
