### PR TITLE
Profile change #1

### PR DESCRIPTION
**Pull request by Dis1309**
solved-
#1 
Changed the details of profile as required.

### CODE REVIEW

**Comment by SameepAher** [comment]
@Dis1309 The changes made in `profiles.json` looks good.

However, as per the issue description, it was asked to put the screenshot in the PR description, not in the project folder.

Make these changes - 

- Remove the `profile.PNG` file.
- Add screenshot in the PR description (you can edit the PR description).

**Also, take a clear screenshot which shows the url as well as the JSON data.**

I'll accept the PR once these changes are made.

**Comment by Dis1309** [comment]
profile1
[]([]([](profile1)))
http://[localhost:3000/profiles](http://localhost:3000/profiles)

**Comment by SameepAher** [comment]
@Dis1309 you need to add a screenshot which returns your profile's data by roll number, just as the issue description states.

**Comment by Dis1309** [comment]
modified version
rollno has been added to the url

**Pull request closed without merging**
