### PR TITLE
maskboy info

### PR DESCRIPTION
**Pull request by maskboyAvi**

### CODE REVIEW

**Comment by SameepAher** [comment]
@maskboyAvi Attach a screenshot which shows the url as well as the JSON data, in your PR description. Also add "Fixes: #1" in your PR description, which makes it clear for what issue this PR is made for.

Carefully read the issue description which clearly states what exactly is needed in the PR.

Otherwise, the code changes looks perfectly fine.

Will accept the PR once the PR description is changed as mentioned above.

**Comment by maskboyAvi** [comment]
#1 Added my details .
Screenshot (71)

**Comment by SameepAher** [comment]
@maskboyAvi you need to add a screenshot which returns your profile's data by roll number, just as the issue description states.

In your case the url should be localhost:3000/profiles/lcs2022007

**Comment by maskboyAvi** [comment]
#1 Added my Details in json file.
Screenshot (72)

**Comment by SameepAher** [comment]
@maskboyAvi Accepted!

**Pull request closed without merging**
