### PR TITLE
aviralhatwal

### PR DESCRIPTION
**Pull request by aviralhatwal**
lcb2022016

### CODE REVIEW

**Comment by SameepAher** [comment]
@aviralhatwal You are not required to make any changes in the `index.html` file. Otherwise, the changes in `profiles.json` look fine.

So,
- just remove any changes in the `index.html` file.
- Add a screenshot which returns your profile's data by roll number (just like the screenshot in #1).
- Add `Fixes: #1` (make sure `#1` links to the issue 1) in the PR description.

Make these changes and I'll accept the PR.

**Comment by SameepAher** [comment]
@aviralhatwal The code changes are correct. Just add a screenshot as mentioned in the issue description.

**Comment by aviralhatwal** [comment]
Screenshot (137)

Fixes: #1

**Comment by aviralhatwal** [comment]
Screenshot (139)

**Comment by SameepAher** [comment]
@aviralhatwal Accepted!

**Pull request closed without merging**
