### PR TITLE
Main

### PR DESCRIPTION
**Pull request by darshbaxi**
Adding profile of lcb2022003

### CODE REVIEW

**Comment by SameepAher** [comment]
@darshbaxi You are required to edit the`profiles.json`, adding / replacing your information.

**Some changes required:**

- There is ***no need*** to edit index.html. So remove any changes you've made in that file.
- There is ***no need*** to create `public/profiles/lcb2022003.json`. You just need to directly add / edit in `profiles.json`. So remove public/profiles/lcb2022003.json from your project folder.
- As the issue description states - Attach a screenshot which shows the url as well as the JSON data, in your PR description.
- Also, add `Fixes: #1` (ensure `#1` links to the issue) in your PR description, which makes it clear for what issue this PR is made for.
- Also change the PR title to something which actually describes the purpose of the PR.

Will accept the PR once these changes are made.

**Comment by darshbaxi** [comment]
Screenshot_20230204_210028
Fixes: #1

**Comment by SameepAher** [comment]
> There is no need to edit index.html. So remove any changes you've made in that file.
  
Just in case you forgot.

**Comment by SameepAher** [comment]
@darshbaxi the changes in `index.html` are still visible. Just make sure `line 14` of `index.html` should be `<a href="./profiles/lcs2020000">/profiles/lcs2020000</a>`.

**Comment by SameepAher** [comment]
@darshbaxi Accepted!

**Pull request closed without merging**
