### PR TITLE
Updating my participation info

### PR DESCRIPTION
**Pull request by Harshs0891**
lcb2022025

### CODE REVIEW

**Comment by SameepAher** [comment]
@Harshs0891 There is no need to edit `index.html` so remove those changes and push again.

Otherwise the code changes in `profiles.json` are fine.

**Comment by SameepAher** [comment]
@Harshs0891 `<a href="./profiles/lcs2020000">/profiles/lcs2020000</a>` was `line 14` in `index.html`. Make the correct changes and push the new code.

Also update the PR description with screenshot (refer to the screenshot in the issue description) and add #Fix: #1" to make it clear about the issue this PR was made for.

**Comment by Harshs0891** [comment]
pr
Fixes: #1

**Comment by SameepAher** [comment]
@Harshs0891 Good work!

**Pull request closed without merging**
