### PR TITLE
Added info of lcb2022015

### PR DESCRIPTION
**Pull request by Arpit1033**

### CODE REVIEW

**Comment by SameepAher** [comment]
@Arpit1033 Attach a screenshot which shows the url as well as the JSON data (refer to the screenshot in #1), in your PR description. Also add "Fixes: https://github.com/iiitl/Participants-API/issues/1" in your PR description, which makes it clear for what issue this PR is made for.

Also, it is not required to make any changes in `index.html`, so remove any of those changes. Otherwise, the code changes in `profiles.json` are perfect.

Push the new code after making these changes and update the PR description. Once done, I'll accept this PR.

**Comment by Arpit1033** [comment]
Profile
Fixes: #1

**Comment by SameepAher** [comment]
> Profile Fixes: #1

@Arpit1033 read the issue carefully. It requires a screenshot which returns your profile's data by roll number (in your case, the url should be http://localhost:3000/profiles/lcb2022015).

**Comment by Arpit1033** [comment]
image
Fixes: #1

**Comment by SameepAher** [comment]
@Arpit1033 Accepted!

**Pull request closed without merging**
